---
title: "Forecasting the age structure of the scientific workforce in Australia"
author: Rob J Hyndman
date: 30 June 2025
toc: false
format:
  presentation-beamer:
    pdf-engine: pdflatex
    knitr:
      opts_chunk:
        dev: "CairoPDF"
    include-in-header: header.tex
    keep-tex: true
    fig-width: 9
    fig-height: 4
highlight-style: tango
execute:
  echo: false
  message: false
  warning: false
  cache: false
abstract: |
  "I will demonstrate how to forecast the age structure of a workforce using demographic growth-balance equations that incorporate functional data components for graduate influx, international mobility, retirement, and mortality. This model adapts the stochastic population framework proposed by Hyndman and Booth (IJF, 2008), substituting the birth component at age 0 with a graduation process at any age, and integrating retirement dynamics alongside a standard mortality process. It accommodates variable graduate influx, international mobility, and aging, through functional data components.
  The model is illustrated by forecasting the future age structure of scientific disciplines in Australia, utilising a variety of data sources. Data limitations are addressed through cohort interpolation and constrained penalised regression splines in order to obtain a workable data set. A combination of local and global ARIMA models is employed to address the temporal dynamics in the time series components.
  By forecasting age structures in disciplines such as Physics and Astronomy, Mathematical Sciences, Chemical Sciences, Earth Sciences, and Biological Sciences, the model informs strategic workforce planning and policy development.
  This forecasting framework not only aids in strategic planning and policy formulation within the scientific community, but also offers a blueprint for other professional sectors seeking to understand workforce dynamics amid demographic shifts."
---


```{r setup, include=FALSE}
#| eval: true
library(targets)

# Set default colors
options(
  ggplot2.discrete.colour = c(
    "#D55E00",
    "#0072B2",
    "#009E73",
    "#CC79A7",
    "#E69F00",
    "#56B4E9",
    "#F0E442"
  ),
  ggplot2.discrete.fill = c(
    "#D55E00",
    "#0072B2",
    "#009E73",
    "#CC79A7",
    "#E69F00",
    "#56B4E9",
    "#F0E442"
  )
)
```

# Labour force participation rates

```{r}
#| label: labour-force
# Labour force participation rates by one-year age groups for 2016 and 2021, along with the average of these two years, which is used as a proxy for 2006 and 2011.
tar_read(fig1)
```

# Working population by year and age

```{r}
#| label: labour-force2
tar_read(fig3)
```

# Retirement intentions

```{r}
#| label: retirement
tar_read(fig6)
```

# Death probabilities

```{r}
#| label: death_prob
tar_read(fig8)
```

# Graduate completions

```{r}
#| label: graduates
tar_read(fig10)
```
